name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is a environments where we can deploy workflow 
        type: choice
        options:
          - dev
          - main
          - stage

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        run: echo "checking code"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: "Build code in docker container"
        run: docker --version
  test:
    needs: [code, build]
    runs-on: ubuntu-latest
    steps:
      - name: "Testing a code"
        run: echo "testing a container"

  deploy:
    needs: [code, build, test]
    runs-on: ubuntu-latest
    steps:
      - name: " Deploying application"
        run: echo "Deploying the application All process Are successfull"


      
