name: Alfaiz Deshmukh 

on:
  push:
    branches: [main]
    paths: 
      - "**.html"

jobs:  
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to freinds 
        run: echo "hello Alfaiz"
  
      - name: Say Hello to username 
        run: echo "Hello $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: showthe version of python & Docker
        run: docker --version && python --version

  Date_time:
    runs-on: ubuntu-latest
    steps:
      - name: show current time
        run: date

      - name: date
        run: echo "Current Date & Time is $(date)"
      
